EventManagement/event/urls.py
from django.urls import path
from django.conf.urls import url

from event import views
from .views import set_Event_Details, event_success, ViewMyEvent, view_event_page, EventEntry  # view_event_page

app_name = 'event'

urlpatterns = [

    # /event/
    url(r'^$', ViewMyEvent, name='index'),

    # event/event/entry
    url('entry/$', EventEntry, name='event-entry'),

    # event/product/2
    url(r'^(?P<pk>[0-9]+)/$', views.EventUpdate.as_view(), name='event-update'),

    url(r'^(?P<pk>[0-9]+)/update$', set_Event_Details, name='event_details'),

    url('success/$', event_success, name='Allevents'),
    # url('details/$', view_event_page, name='viewEventPage'),
    # url(r'^(?P<pk>[0-9]+)/details$', view_event_page, name='details'),
    # url(r'^details/eventDetail-(?P<parameter>[\w-]+).html', view_event_page, name="viewEventPage"),

    # url(r'^(?P<pk>[0-9]+)/$', views.EventAdvancedUpdate.as_view(), name='event-advanced-update'),

    # event/product/(?P<pk>[0-9]+)/delete
    url(r'^album/(?P<pk>[0-9]+)/delete$', views.EventDelete.as_view(), name='event-delete'),
    # path('', reg_group.home, name='home'),
    # url(r'^(?P<pk>\d+)/$', view_event_page, name='details'),
    url(r'^detail/$', view_event_page, name="details"),

]

EventManagement/eventManagement/urls.py
from django.conf.urls import url
from django.contrib import admin
from .admin import event_Management_Admin_Site
from django.urls import path, include
from reg_group.views import client, agency, reg_group, vendor
from requestBrief.views import popup, request_view, servicerequest_view, servicerequest_success, servicematch, servicematch_success_showlittle
from requestBrief.views import servicematch_success, servicematch_message
from requestBrief.views import request_success, match, match_success, client_request_history, match_message , agencyclient_message
from relation.views import AdSearchView
from vendor.views import vendorlist_view
from agency.views import agency_vendor_success, agency_message, agencylist_view
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from tickets.views import ViewTicket, TicketEntry

admin.site.site_header = "jisha"
admin.site.site_title = "jisha"
admin.site.index_title = "jisha"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', event_Management_Admin_Site.urls),
    path('', include('reg_group.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', reg_group.SignUpView.as_view(), name='signup'),
    path('accounts/signup/client/', client.ClientSignUpView.as_view(), name='client_signup'),
    path('accounts/signup/agency/', agency.AgencySignUpView.as_view(), name='agency_signup'),
    path('accounts/signup/vendor/', vendor.VendorSignUpView.as_view(), name='vendor_signup'),

    path('search/', agency.SearchResultsView.as_view(), name='search_results'),

    path('client/myrequest/', request_view, name='popup'),
    path('client/agencylist', agencylist_view, name='agencylistview'),
    path('client/vendorlist', vendorlist_view, name='vendorlistview'),

    path('client/myservicerequest/', servicerequest_view, name='servicepopup'),
    path('client/myBrief/', request_success, name='createBrief'),
    path('client/myserviceBrief/', servicerequest_success, name='servicecreateBrief'),
    path('client/mymatch/', match, name='mymatch'),
    path('client/myservicematch/', servicematch, name='myservicematch'),
    path('client/history/', client_request_history, name='client_request_history'),
    path('client/mymatch/agency/', match_success, name='agency_match'),

    path('agency/vendor/', agency_vendor_success, name='agency_vendor_match'),

    path('client/myservicematch/vendor/', servicematch_success, name='vendor_match'),
    path('client/myservicematch/', servicematch_success_showlittle, name='vendor_match_little'),
    path('client/mymatch/agency/message', match_message, name='agency_message'),
    path('client/myservicematch/vendor/message', servicematch_message, name='vendor_message'),
    path('agency/profile/preference/message', agency_message, name='agency_reply_message'),
    path('client/mymatch/agencyclient/message', agencyclient_message, name='agencyclient_message'),

    path('agency/search/', AdSearchView.as_view(), name='search'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('feedback/', include('feedback.urls')),

    url(r'^ticket/', TicketEntry, name='view_ticket'),
    url(r'^event/', include('event.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EventManagement/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Event Management{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontello-2f186091/css/fontello.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    {% if user.is_authenticated and user.is_agency %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/agency.css' %}">
    {% elif user.is_authenticated and user.is_vendor %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/vendor.css' %}">
    {% else %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/client.css' %}">
    {% endif %}
  </head>
  <body>
    <!--<a href="https://github.com/sibtc/django-multiple-user-types-example"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"></a>-->
    <div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="row">
            <div class="col-6">
              <h1 class="logo">
                <a href="{% url 'home' %}">
                  Event Management
                  {% if user.is_authenticated %}
                    {% if user.is_agency %}
                      <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Agency profile"></span>
                    {% elif user.is_vendor %}
                      <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Vendor profile"></span>
                    {% else %}
                      <span class="icon-graduation-cap" data-toggle="tooltip" data-placement="right" title="Client profile"></span>
                    {% endif %}
                  {% endif %}
                </a>
              </h1>
            </div>
            <div class="col-6 text-right">
              {% if user.is_authenticated %}
                <p class="pt-3">Logged in as <strong>{{ user.username }}</strong>. <a href="{% url 'logout' %}">Log out</a>.</p>
              {% else %}
                <a href="{% url 'login' %}" class="btn btn-light" role="button">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary" role="button">Sign up</a>
              {% endif %}
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% block content %}
              {% endblock %}
            </div>
          </div>
<!--          <footer>
            <a href="https://simpleisbetterthancomplex.com">© SimpleIsBetterThanComplex.com</a>
            /
            <a href="https://simpleisbetterthancomplex.com/tutorial/2018/01/18/how-to-implement-multiple-user-types-with-django.html">Read more about this example</a>
            /
            <a href="https://github.com/sibtc/django-multiple-user-types-example">GitHub repository</a>
          </footer>-->
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
    </script>
  </body>
</html>

EventManagement/templates/base2.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <title>Welcome</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">

</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
    {{ message }}
</div>
{% endfor %}
{% endif %}


<div class="site-wrap" id="home-section">

    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
                <span class="icon-close2 js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>


    <header class="site-navbar js-sticky-header site-navbar-target" role="banner">

        <div class="container">
            <div class="row align-items-center position-relative">


                <div class="site-logo">
                    <a href="{% url 'home' %}" class="text-black"><span class="text-primary">Manage Your event</a>
                </div>

                <nav class="site-navigation text-center ml-auto" role="navigation">

                    <ul class="site-menu main-menu js-clone-nav ml-auto d-none d-lg-block">


                        <li><a href="#about-section" class="nav-link">About</a></li>
                        <li><a href="#services-section" class="nav-link">Services</a></li>

                        {% if user.is_authenticated %}
                        {% if user.is_agency %}
                        <li><a href="{% url 'event:index' %}" class="nav-link">Create Event</a></li>
                        {% endif %}
                        {% endif %}

                        {% if user.is_client%}
                        <li><a href="{% url 'popup' %}" class="nav-link">Request Event</a></li>
                        {% else %}
                        <li><a href="#investors-section" class="nav-link">Recent Events</a></li>
                        {% endif %}

                        {% if user.is_authenticated %}
                        <li><a href="/client/profile" class="nav-link">Profile</a></li>
                        <li><a href="/logout" class="nav-link">Logout</a></li>
                        {% else %}
                        <!--<li><a href="/register" class="nav-link">Register</a></li>-->
                        <li><a href="/accounts/signup" class="nav-link">Register</a></li>
                        <li><a href="accounts/login" class="nav-link">Login</a></li>
                        {% endif %}

                        <li><a href="#press-section" class="nav-link">Popular Vendors</a></li>


                        <li><a href="#blog-section" class="nav-link">Blog</a></li>
                        <li><a href="#contact-section" class="nav-link">Contact</a></li>
                    </ul>
                </nav>


                <div class="toggle-button d-inline-block d-lg-none"><a href="#"
                                                                       class="site-menu-toggle py-5 js-menu-toggle text-black"><span
                        class="icon-menu h3"></span></a></div>

            </div>
        </div>

    </header>

</div>
{% block content %} {% endblock %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>


</body>

</html>

EventManagement/templates/google_map.html
<html >
<body onLoad="initialize()">
                  <div class="col-sm-offset-1" id="map_canvas" style="width:500; height:500"></div>
                  <br>
                  <input type="text" id="lat">
                  <input type="text" id="lng">
<script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
<style>
  body{
    text-align:center;
  }
  .gmap3{
    margin: 20px auto;
    border: 1px dashed #C0C0C0;
    width: 500px;
    height: 500px;
  }
</style>
<script type="text/javascript">
   var map;
 function initialize() {
 var myLatlng = new google.maps.LatLng(36.85341604753753,10.176080866332995);
 var myOptions = {
 zoom: 14,
 minZoom:14,
 center: myLatlng,
 draggable:false,
 mapTypeId: google.maps.MapTypeId.SATELLITE
 }
map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
 var marker = new google.maps.Marker({


draggable: true,
position: myLatlng,
map: map,
  });
google.maps.event.addListener(marker, 'dragend', function (event) {
document.getElementById("lat").value = this.getPosition().lat();
document.getElementById("lng").value = this.getPosition().lng();
}
);
}
</script>
</body>
</html>

EventManagement/templates/new_base.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <title>Welcome</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
    {{ message }}
</div>
{% endfor %}
{% endif %}

{% block content %} {% endblock %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

EventManagement/templates/profile_base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>


{% block content %}
{% endblock %}
</body>
</html>

EventManagement/templates/search_results.html
<html>
<head>
<title> Searched Result </title>
<center>
<br><br><h1>Search Results</h1><br><br>
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">
    <meta charset="UTF-8">    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>

.checked {
  color: orange;
}
        body  {
        background-image: linear-gradient(#fffdfe, #ccd5ff, #f2d0ff);

        }

    </style>
  </head>
<body>
<div class="row">
<div class="col-sm ">
<ul>
  {% for user in object_list %}
    <li>
      <font color=#00008b style="width: 100%"> User Name:  {{ user.username }} </font>
      <font color=#008b8b style="width: 100%"> Email:  {{ user.email }} </font><br><br>
    </li>
  {% endfor %}
</ul>
</div>
</div>
</body>
</center>
</html>